### ISSUE TITLE
Pre-requisite installing NocMigR2

### ISSUE THREAD

**Issue by TonyRinaud** [mottensmann/NocMigR2#1]
Hi Meinolf!

Finely got a new audiomoth! So of course I ran into your package instantly ;)

Just as a comment, I was not able to install the package straight away:
`devtools::install_github("mottensmann/NocMigR2")` gave me:
> Using GitHub PAT from the git credential store.
> Error: Failed to install 'unknown package' from GitHub:
>   HTTP error 401.
>   Bad credentials
> 
>   Rate limit remaining: 55/60
>   Rate limit reset at: 2024-07-05 11:13:05 UTC

So I had to set a token from github in order to install your package using:
`usethis::create_github_token()`

then I set this token in the R environment:
`Sys.setenv(GITHUB_PAT = "your token")`

then I could install:
`devtools::install_github("mottensmann/NocMigR2")`

I never had this issue with installing github repo before so people might want this info if stuck installing your package!

Cheers 
Tony

**Comment by mottensmann** [comment]
Hey Tony,

many thanks for the heads-up on the GitHub PAT-issue! 

If I understand correctly, the problem is due to a limit of max 60 unauthenticated requests per hour querying the GitHub REST API. However, once authenticated (using a PAT) the rate limit is much enhanced, and installing packages (not specific to `NocMigR2`!) is practically without restrictions. 

Here are some references:
* [GitHub REST API rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28)
* [stackoverflow](https://stackoverflow.com/questions/70908295/failed-to-install-unknown-package-from-github)
